# -*- coding: utf-8 -*-
"""AD-7/1/25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJdNSxwHNGFIJQ55kPw1s4t8kzhajNAj
"""

a='hello world'
b=a.upper()
print(b)

a='HELLO WORLD'
b=a.lower()
print(b)

a='hello world'
b=a.replace('hello','hi')
print(b)

a='123asa'
b=
print(b)

a=range(10)
b=list(a)
print(b)

my_list=list(range(5,15,20))
print(my_list)

def add_numbers(a,b):
    result=a+b
    return result
result2=add_numbers(10,2)
print(result2)

function with *args
def Calculate_sum(*args):
  total=sum(args)
  return total
print("Sum of 1,2,3,4 :",Calculate_sum(1,2,3,4,))
print("Sum of 1,2,3,4 :",Calculate_sum(1,2,3,4,5))

add=lambda x,y :x+y
result =add(3,5)
print(result)

is_palindrome=lambda s:s==s[::-1]
print(is_palindrome("radar"))

text = "hello world"

uppercase_text = text.upper()

starts_with_hello = text.startswith("hello")

replaced_text = text.replace("world", "Python")

position_of_o = text.find('o')


print(f"Original text: {text}")
print(f"Uppercase: {uppercase_text}")
print(f"Starts with 'hello': {starts_with_hello}")
print(f"Replaced text: {replaced_text}")
print(f"Position of 'o': {position_of_o}")

numbers = [10, 5, 3, 8, 12]
numbers.append(15)
numbers.remove(3)
numbers.sort()
numbers.reverse()
total_sum = sum(numbers)
print(f"Modified list: {numbers}")
print(f"Sum of all elements: {total_sum}")