# -*- coding: utf-8 -*-
"""NLP pipelines demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12WwjCKIgOlrrjSKe35nUYMMUBKiijmA6
"""

from transformers import pipeline

qa_pipeline = pipeline("question-answering")

context = """The Eiffel Tower is one of the most famous landmarks in the world.
It was constructed in 1889 in Paris, France, and stands at a height of 330 meters."""

question = "Where is the Eiffel Tower located?"

result = qa_pipeline(question=question, context=context)
print(result)

summarizer = pipeline("summarization")

text = """Artificial Intelligence (AI) is transforming industries by automating
tasks, improving efficiency, and enabling data-driven decision-making.
Companies across healthcare, finance, and transportation are integrating AI
to enhance productivity and customer experiences."""

summary = summarizer(text, max_length=30, min_length=10, do_sample=False)
print(summary)

from transformers import pipeline
import pandas as pd

# Load table QA pipeline
table_qa = pipeline("table-question-answering")

# Create a simple table
data = {
    "Name": ["Alice", "Bob"],
    "Age": ["25", "30"],
    "City": ["New York", "San Francisco"]
}
table = pd.DataFrame.from_dict(data)

# Ask a question about the table
question = "Where does Bob live?"
result = table_qa(table=table, query=question)
print(result)

text2text = pipeline("text2text-generation")

text = "Convert this sentence into a question: The sky is blue."
result = text2text(text)
print(result)

classifier = pipeline("text-classification")

text = "I absolutely love this new AI model!"
result = classifier(text)
print(result)

generator = pipeline("text-generation")

prompt = "The future of AI is"
result = generator(prompt, max_length=30, num_return_sequences=1)
print(result)

ner_pipeline = pipeline("token-classification", grouped_entities=True)

text = "Elon Musk founded SpaceX in 2002 and acquired Twitter in 2022."
result = ner_pipeline(text)
print(result)

translator = pipeline("translation_en_to_fr")

text = "Hello, how are you?"
result = translator(text)
print(result)

zero_shot = pipeline("zero-shot-classification")

text = "I love playing football during the weekends."
labels = ["sports", "technology", "food"]

result = zero_shot(text, candidate_labels=labels)
print(result['labels'])
print(result['scores'])











